### PR TITLE
Add initial Mkdocs landing page

### PR DESCRIPTION
**Pull request by ericholscher**
I got part of the way through doing the mkdocs testomonials,
but didn't want to spend the time to get the right logos, etc.

We can add them once we know who we should be highlighting.

----
:books: Documentation preview :books:: https://read-the-docs-website--222.com.readthedocs.build/

Refs https://github.com/readthedocs/website/issues/218

### CODE REVIEW

**Comment by ericholscher** [comment]
@humitos would love if you get a chance to peek at this, and we can get it shipped and starting to get SEO, and iterate from there.

**Comment by humitos** [comment]
I won't be able to take a look at it today, but I'll do it on Monday. I can review and merge while you are out so we start getting SEO here.

**Comment by humitos** [comment]
... or the other way around ... you merge and deploy, and I review and propose changes in another PR. Either way.

**Comment by ericholscher** [comment]
Cool, I think there's minimal downside to have it shipped and nobody looking at it, so willl go ahead and merge 👍

**Pull request merged**
