### PR TITLE
Fix blog templates

### PR DESCRIPTION
**Pull request by agjohnson**
We did an original pass at the blog templates, but they needed clean up, fixes, and a better structure.

I jumped in here so we could at least start experimenting with putting all our website content in one place. This won't be super usable until we decide to do something with our newsletter integration though.

Some changes included here:

- Clean up the article display template
- Add category and tags to the display template
- Clean up the listing template
- Add category to the list template
- Use a macro for article cards on listing page, instead of repeating content
- Add category and tag listing templates, for linking to category pages and tag listing pages from the individual blog posts
- Fix the RSS/Atom feeds, only output one item per feed to make our newletter integration work
- Replace the default image with a generated SVG for now

Draft PR with some blog posts, to illustrate what this PR actually does: https://github.com/readthedocs/website/pull/202

----
:books: Documentation preview :books:: https://read-the-docs-website--201.com.readthedocs.build/

### CODE REVIEW

**Comment by agjohnson** [comment]
This PR won't be super reviewable, but there is some copy to eyeball here at least.

A better view into this PR is at #202. Here are some URLs:

- https://read-the-docs-website--202.com.readthedocs.build/blog/ -- The main blog listing page
- https://read-the-docs-website--202.com.readthedocs.build/blog/2023/03/read-the-docs-website-migration/ -- Example blog post ported over to Pelican, some slight differences
- https://read-the-docs-website--202.com.readthedocs.build/blog/category/changelog.html -- Category listing page, if you click the category on the blog post page
- https://read-the-docs-website--202.com.readthedocs.build/blog/tag/website.html -- tag listing page, if you click a tag from the blog post dropdown

This one doesn't work apparently, but it was working in dev:

- https://read-the-docs-website--202.com.readthedocs.build/en/202/blog/feed.rss

I'm guessing there is something that needs to be done on the feed base URL or something. The PR build could be interfering here?

**Comment by ericholscher** [comment]
Those example pages look really nice 💯

**Review by ericholscher — APPROVED** [review]
I'm 👍 merging this and leaving the content PR to be where we decide on how to move forward, but not let these styles get out of sync.

**Comment by agjohnson** [comment]
Yeah, I was thinking we could merge this pretty quick just to have things ready for authoring content on the blog when we decide to try it out. I've updated the underlying issue:

- https://github.com/readthedocs/website/issues/33

I'm guessing at very least we'll have to fix up a remaining issue with the feed URL, but that is probably a minor thing like a config variable is off.

**Pull request merged**
