### PR TITLE
Pricing: hide "Basic" plan and show "Enterprise"

### LINKED ISSUE #289: Pricing: remove "Basic plan" and add "Enterprise plan"
We are currently showing Basic, Advanced and Pro. We would like to change this to show Advanced, Pro and Enterprise.

We talked about keeping Basic below the fold in case there are people wanting to use Read the Docs at a lower price (school, universities, and simlar). However, most of the people should not even see this option 😄 

* Enterprise plan should show support for SAML
* Keep the Basic plan in the comparison table
* Mention custom invoicing on Enterprise

### PR DESCRIPTION
**Pull request by humitos**
I copied the text and features from http://localhost:8080/pricing/enterprise/

Screenshot_2024-07-24_16-21-26

Closes #289

----
📚 Documentation preview 📚: https://readthedocs-about--316.org.readthedocs.build/

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]
This looks like a great start. I think we should still probably mention the Basic plans price _somewhere_ on the page, since this is a pricing page after all. Not sure the best UX for it, but I think its at least worth having as a small callout, perhaps at the bottom? If it's a pain, I'm also fine shipping this without changes.

**Comment by humitos** [comment]
Yeah. I thought the same but I didn't find an obvious easy to mention it.

I kept the comparison table that mention Basic, tho, so the features are differentiated at least.

Do you have an idea for this?

Since we don't want to promote it, I think that not having a big card is fine. People really wanting to pay 50$ a month will figure it out from the subscription page anyways 🤷‍♂️

**Comment by ericholscher** [comment]
Perhaps just put the pricing in the comparison table? 🤔

**Comment by humitos** [comment]
> If it's a pain, I'm also fine shipping this without changes.

I will probably take this sentence 😉  and move forward with this PR. We can open an new issue to deal with Basic price in the next immediate iteration (next Sprint?)

**Comment by ericholscher** [comment]
Follow up here: https://github.com/readthedocs/website/pull/321

**Pull request merged**
